openapi: 3.0.0
servers:
  - description: Your localhost server
    url: http://127.0.0.1:5000
info:
  description: The one and only API combining astrology and webhooks. It allows you to retrieve information about the planets of the solar system provided by NASA
  version: 1.0.0
  x-logo:
    url: 'https://raw.githubusercontent.com/steroman/flask-planets/main/docs/assets/nasa-logo.png'
    altText: Nasa Logo
  title: Planets and Webhooks
  contact:
    email: doyou@space.out
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
tags:
  - name: planets
    description: Information about the planets of the solar system.
paths:
  /planets:
    get:
      tags:
        - planets
      summary: Planet List
      operationId: GetPlanetList
      description: Get the list of planets of the solar system.
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets'
      responses:
        200:
          description: Planet list successfully retrieved.
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/PlanetList"
        500:
          description: Internal Server Error
  /planets/{id}:
    get:
      tags:
       - planets
      summary: Planet Info
      operationId: GetPlanetInfo
      description: Get the planet info using their position as the ID.
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets/1'
      parameters:
        - in: path
          required: true
          description: The planet's order from the Sun.
          name: id
          schema:
            type: number
            minimum: 1
            maximum: 8
            example: 4
      responses:
        200:
          description: Planet information correctly retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanetInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/PlanetInfo'
components:
  schemas:
    PlanetInfo:
      description: The planet information data model.
      properties:
        moons:
          type: integer
          example: 82
          description: The total number of moons for the planet. It includes its confirmed and provisional moons.
        name:
          type: string
          example: Mercury
          description: The official name of the planet according to NASA.
        position:
          type: integer
          minimum: 1
          maximum: 8
          example: 4
          description: The order of the planet from the Sun.
    PlanetList:
      description: The planet list data model.
      type: array
      items:
        $ref: '#/components/schemas/PlanetInfo'
