openapi: 3.0.3
servers:
  - description: Your localhost server
    url: http://127.0.0.1:5000
info:
  description: The one and only API combining astrology and webhooks. It allows you to retrieve information about the planets of the solar system provided by NASA.
  version: 1.0.0
  x-logo:
    url: 'https://raw.githubusercontent.com/steroman/flask-planets/main/docs/assets/nasa-logo.png'
    altText: Nasa Logo
  title: Planets and Webhooks
  contact:
    email: doyou@space.out
    name: NASA
    url: 'www.nasa.org'
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
tags:
  - name: planets
    description: Information about the planets of the solar system
  - name: webhooks
    description: Webhooks allow you to log requests made to the API
externalDocs:
  description: Source Data
  url: https://solarsystem.nasa.gov/moons/in-depth/
paths:
  /planets:
    get:
      tags:
        - planets
      summary: Planet List
      operationId: GetPlanetList
      description: Get the list of planets of the solar system
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets'
      responses:
        200:
          description: Planet list successfully retrieved
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/PlanetList"
        500:
          description: Internal Server Error
  /planets/{id}:
    get:
      tags:
       - planets
      summary: Planet Info
      operationId: GetPlanetInfo
      description: Get the planet info using their position as the ID
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets/1'
      parameters:
        - in: path
          required: true
          description: The planet's order from the Sun
          name: id
          schema:
            type: integer
            minimum: 1
            maximum: 8
            example: 4
      responses:
        200:
          description: Planet information correctly retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanetInfo'
  /webhook:
    get:
      tags:
       - webhooks
      summary: Get Webhook
      operationId: GetWebhook
      description: Get a list of wehooks
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/webhook'
      responses:
        200:
          description: The list of webhooks
    post:
      tags:
       - webhooks
      summary: Post Webhook
      operationId: PostWebhook
      description: Subscribe to the webhook
      x-codeSamples:
        - lang: C
          source: curl --location --request POST '127.0.0.1:5000/webhook'
      responses:
        200:
          description: Subscribed to the webhook
components:
  schemas:
    PlanetInfo:
      description: The planet information data model
      properties:
        name:
          type: string
          example: Saturn
          description: The official name of the planet according to NASA
        position:
          type: integer
          example: 5
          description: The order of the planet from the Sun
        moons:
          type: integer
          example: 82
          description: The total number of moons for the planet. It includes its confirmed and provisional moons.
    PlanetList:
      description: The planet list data model
      type: array
      items:
        $ref: '#/components/schemas/PlanetInfo'
