openapi: 3.0.0
servers:
  - description: Your localhost server
    url: http://127.0.0.1:5000
info:
  description: The one and only API combining astrology and webhooks. It allows you to retrieve information about the planets of the solar system provided by (Nasa Link)
  version: 1.0.0
  x-logo:
    url: 'https://raw.githubusercontent.com/steroman/flask-planets/main/docs/assets/nasa-logo.png'
    altText: Nasa Logo
  title: Planets and Webhooks
  contact:
    email: doyou@space.out
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
tags:
  - name: planets
    description: Information about the planets of the solar system.
paths:
  /planets:
    get:
      tags:
        - planets
      summary: Planet List
      operationId: GetPlanetList
      description: Get the list of planets of the solar system.
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlanetList"
        '500':
          description: Internal Server Error
  /planets/{id}:
    get:
      tags:
       - planets
      summary: Planet Info by ID
      operationId: GetPlanetInfo
      description: Get the planet info using their position as the ID.
      x-codeSamples:
        - lang: C
          source: curl --location --request GET '127.0.0.1:5000/planets/1'
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: number
            minimum: 1
            maximum: 8
      responses:
        '200':
          description: The list of planets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlanetInfo'
components:
  schemas:
    PlanetInfo:
      type: object
      properties:
        name:
          description: The name of the planet
          type: string
          example: Mercury
        position:
          description: The planet order starting from the Sun
          type: number
          example: 1
        moons:
          description: The total number of moons for the planet, which is the sum of the confirmed and provisional moons provided by NASA
          type: number
          example: 82
      example:
        name: Mercury
        position: 1
        moons: 82
      description: The reference data model of the planet information.
    PlanetList:
      description: The data model for the list of planets. The model is an array of PlanetInfo objects.
